(ns sova.statecharts.refit.feed-golden
  "r8a golden table (generated from feed-table, reviewed against r8a's lists): every authored transition
   of the eleven statecharts → its feed class. A class flip, a new or a removed transition fails feed-test;
   regenerate only with a reviewed change.")

(def golden
  {
   ["baton" ":baton" [":session/retire"] "[:retired]" 0] :feed
   ["build" ":build" [":session/retire"] "[:retired]" 0] :feed
   ["project" ":project" [":link/moved"] "[]" 0] :quiet
   ["project" ":project" [":sova.statecharts/flush"] "[]" 0] :quiet
   ["project" ":project" [":started/noted"] "[]" 0] :quiet
   ["project" ":project" [":session/prompt"] "[]" 0] :feed
   ["decision" ":edited-in-spec" [":effect/done"] "[:as-promoted]" 0] :feed
   ["baton" ":baton" [":hold/approve"] "[]" 0] :correction
   ["baton" ":baton" [":hold/waiting"] "[]" 0] :feed
   ["build" ":build" [":hold/approve"] "[]" 0] :correction
   ["build" ":build" [":hold/waiting"] "[]" 0] :feed
   ["item" ":item" [":hold/approve"] "[]" 0] :correction
   ["item" ":item" [":hold/waiting"] "[]" 0] :feed
   ["person" ":person" [":hold/approve"] "[]" 0] :correction
   ["person" ":person" [":hold/waiting"] "[]" 0] :feed
   ["project" ":project" [":hold/approve"] "[]" 0] :correction
   ["project" ":project" [":hold/waiting"] "[]" 0] :feed
   ["reconciler" ":reconciler" [":hold/approve"] "[]" 0] :correction
   ["reconciler" ":reconciler" [":hold/waiting"] "[]" 0] :feed
   ["baton" ":at-limit" [] "[:under]" 0] :quiet
   ["baton" ":baton" [":baton/abilities"] "[]" 0] :feed
   ["baton" ":baton" [":baton/extend"] "[]" 0] :feed
   ["project" ":project" [":outreach/send"] "[]" 0] :feed
   ["baton" ":baton" [":baton/hide"] "[]" 0] :feed
   ["baton" ":baton" [":baton/propose"] "[]" 0] :feed
   ["baton" ":baton" [":baton/record-decision"] "[]" 0] :feed
   ["baton" ":baton" [":baton/record-decision"] "[]" 1] :feed
   ["baton" ":baton" [":budget/recount"] "[]" 0] :quiet
   ["baton" ":baton" [":hold/cancel"] "[]" 0] :correction
   ["baton" ":baton" [":link/moved"] "[]" 0] :quiet
   ["baton" ":baton" [":link/moved"] "[]" 1] :quiet
   ["baton" ":baton" [":message/refused"] "[]" 0] :quiet
   ["baton" ":course-born" [] "[:pool]" 0] :feed
   ["baton" ":course-born" [] "[:with-operator]" 0] :feed
   ["baton" ":course-born" [] "[:with-person]" 0] :feed
   ["baton" ":done" [":baton/close"] "[:closed]" 0] :feed
   ["baton" ":pool" [":offer/reach"] "[]" 0] :feed
   ["baton" ":leased" [":baton/message"] "[:leased]" 0] :feed
   ["baton" ":leased" [":lease/lapse"] "[:pool]" 0] :feed
   ["baton" ":leased" [":lease/renew"] "[:leased]" 0] :quiet
   ["baton" ":open" [] "[:with-operator]" 0] :feed
   ["baton" ":open" [":baton/close"] "[:closed]" 0] :feed
   ["baton" ":open" [":baton/goal-done"] "[:done]" 0] :feed
   ["baton" ":open" [":baton/hand-to"] "[:with-operator]" 0] :feed
   ["baton" ":open" [":baton/hand-to"] "[:with-person]" 0] :feed
   ["baton" ":open" [":baton/handoff"] "[:with-person]" 0] :feed
   ["baton" ":open" [":baton/handoff"] "[]" 0] :feed
   ["baton" ":open" [":baton/message"] "[:leased]" 0] :feed
   ["baton" ":open" [":baton/message"] "[]" 0] :feed
   ["baton" ":open" [":baton/offer"] "[:pool]" 0] :feed
   ["baton" ":open" [":baton/offer"] "[]" 0] :feed
   ["baton" ":open" [":baton/take-back"] "[:with-operator]" 0] :feed
   ["baton" ":open" [":baton/take-back"] "[]" 0] :feed
   ["baton" ":open" [":baton/withdraw"] "[:with-operator]" 0] :feed
   ["baton" ":open" [":baton/withdraw"] "[]" 0] :feed
   ["baton" ":open" [":person/left"] "[:with-operator]" 0] :feed
   ["baton" ":open" [":person/left"] "[]" 0] :feed
   ["baton" ":reply-idle" [":baton/message"] "[:reply-starting]" 0] :feed
   ["baton" ":reply-idle" [":reply/starting"] "[:reply-starting]" 0] :quiet
   ["baton" ":reply-idle" [":reply/writing"] "[:reply-writing]" 0] :quiet
   ["baton" ":reply-starting" [":message/refused"] "[:reply-idle]" 0] :quiet
   ["baton" ":reply-starting" [":reply/ended"] "[:reply-idle]" 0] :quiet
   ["baton" ":reply-starting" [":reply/starting"] "[]" 0] :quiet
   ["baton" ":reply-starting" [":reply/stop"] "[:reply-stopping]" 0] :quiet
   ["baton" ":reply-starting" [":reply/writing"] "[:reply-writing]" 0] :quiet
   ["baton" ":reply-stopping" [":reply/ended"] "[:reply-idle]" 0] :quiet
   ["baton" ":reply-writing" [":reply/ended"] "[:reply-idle]" 0] :quiet
   ["baton" ":reply-writing" [":reply/stop"] "[:reply-stopping]" 0] :quiet
   ["baton" ":under" [] "[:at-limit]" 0] :quiet
   ["baton" ":wrapup-due" [] "[:wrapup-running]" 0] :feed
   ["baton" ":wrapup-failed" [":baton/wrapup-retry"] "[:wrapup-running]" 0] :feed
   ["baton" ":wrapup-none" [] "[:wrapup-due]" 0] :feed
   ["baton" ":wrapup-none" [] "[:wrapup-skipped]" 0] :feed
   ["baton" ":wrapup-running" [":sova/resumed"] "[:wrapup-failed]" 0] :feed
   ["baton" ":wrapup-running" [":wrapup/finished"] "[:wrapup-done]" 0] :feed
   ["baton" ":wrapup-running" [":wrapup/overdue"] "[:wrapup-failed]" 0] :feed
   ["baton" ":wrapup-running" [":wrapup/stopped"] "[:wrapup-failed]" 0] :feed
   ["build" ":build" [":build/prompt"] "[]" 0] :feed
   ["build" ":build" [":correct/merged"] "[]" 0] :correction
   ["build" ":build" [":effect/done"] "[]" 0] :quiet
   ["build" ":build" [":effect/failed"] "[]" 0] :quiet
   ["build" ":build" [":git/probe"] "[]" 0] :quiet
   ["build" ":build" [":hold/cancel"] "[]" 0] :correction
   ["build" ":build" [":sova.statecharts/flush"] "[]" 0] :quiet
   ["build" ":build" [":workers/changed"] "[]" 0] :quiet
   ["build" ":making-worktree" [":effect/done"] "[:setting-mode]" 0] :feed
   ["build" ":making-worktree" [":effect/failed"] "[:not-started]" 0] :feed
   ["build" ":merge-idle" [":build/merge"] "[:merging]" 0] :feed
   ["build" ":merge-idle" [":build/remove-worktree"] "[]" 0] :feed
   ["build" ":merged" [":git/probe"] "[:new-since-merge]" 0] :feed
   ["build" ":merged" [":git/probe"] "[:no-commits]" 0] :feed
   ["build" ":merged" [":git/probe"] "[:unmerged]" 0] :feed
   ["build" ":merging" [":effect/done"] "[:merge-idle]" 0] :feed
   ["build" ":merging" [":effect/failed"] "[:merge-idle]" 0] :feed
   ["build" ":new-since-merge" [":git/probe"] "[:merged]" 0] :feed
   ["build" ":new-since-merge" [":git/probe"] "[:no-commits]" 0] :feed
   ["build" ":new-since-merge" [":git/probe"] "[:unmerged]" 0] :feed
   ["build" ":no-commits" [":git/probe"] "[:merged]" 0] :feed
   ["build" ":no-commits" [":git/probe"] "[:new-since-merge]" 0] :feed
   ["build" ":no-commits" [":git/probe"] "[:unmerged]" 0] :feed
   ["build" ":prompting" [":effect/done"] "[:ready]" 0] :feed
   ["build" ":prompting" [":effect/failed"] "[:ready]" 0] :feed
   ["build" ":setting-mode" [":effect/done"] "[:prompting]" 0] :feed
   ["build" ":setting-mode" [":effect/done"] "[:ready]" 0] :feed
   ["build" ":setting-mode" [":effect/failed"] "[:ready]" 0] :feed
   ["build" ":tree" [":tree/removed"] "[:tree-removed]" 0] :feed
   ["build" ":tree-missing" [":git/probe"] "[:tree-open]" 0] :feed
   ["build" ":tree-missing" [":git/probe"] "[:tree-removed]" 0] :feed
   ["build" ":tree-missing" [":git/probe"] "[:tree-root]" 0] :feed
   ["build" ":tree-open" [] "[:tree-root]" 0] :feed
   ["build" ":tree-open" [":git/probe"] "[:tree-missing]" 0] :feed
   ["build" ":tree-open" [":git/probe"] "[:tree-removed]" 0] :feed
   ["build" ":tree-open" [":git/probe"] "[:tree-root]" 0] :feed
   ["build" ":turn-failed" [":turn/started"] "[:working]" 0] :quiet
   ["build" ":turn-idle" [":turn/started"] "[:working]" 0] :quiet
   ["build" ":unmerged" [":git/probe"] "[:merged]" 0] :feed
   ["build" ":unmerged" [":git/probe"] "[:new-since-merge]" 0] :feed
   ["build" ":unmerged" [":git/probe"] "[:no-commits]" 0] :feed
   ["build" ":working" [":turn/ended"] "[:turn-failed]" 0] :quiet
   ["build" ":working" [":turn/ended"] "[:turn-idle]" 0] :quiet
   ["conflict" ":conflict" [":effect/done"] "[]" 0] :quiet
   ["conflict" ":conflict" [":hold/cancel"] "[]" 0] :correction
   ["conflict" ":conflict" [":sova.statecharts/flush"] "[]" 0] :quiet
   ["conflict" ":conflict-born" [] "[:routed-to-operator]" 0] :feed
   ["conflict" ":conflict-born" [] "[:routed-to-person]" 0] :feed
   ["conflict" ":conflict-born" [] "[:unrouted]" 0] :feed
   ["conflict" ":routed-to-operator" [":conflict/reroute"] "[:routed-to-operator]" 0] :feed
   ["conflict" ":routed-to-operator" [":conflict/reroute"] "[:routed-to-person]" 0] :feed
   ["conflict" ":routed-to-operator" [":conflict/reroute"] "[]" 0] :feed
   ["conflict" ":routed-to-operator" [":conflict/resolved"] "[:settled]" 0] :feed
   ["conflict" ":routed-to-operator" [":conflict/settle"] "[:settled]" 0] :feed
   ["conflict" ":routed-to-operator" [":link/moved"] "[:unrouted]" 0] :feed
   ["conflict" ":routed-to-person" [":conflict/reroute"] "[:routed-to-operator]" 0] :feed
   ["conflict" ":routed-to-person" [":conflict/reroute"] "[:routed-to-person]" 0] :feed
   ["conflict" ":routed-to-person" [":conflict/reroute"] "[]" 0] :feed
   ["conflict" ":routed-to-person" [":conflict/resolved"] "[:settled]" 0] :feed
   ["conflict" ":routed-to-person" [":conflict/settle"] "[:settled]" 0] :feed
   ["conflict" ":routed-to-person" [":link/moved"] "[:unrouted]" 0] :feed
   ["conflict" ":unrouted" [":conflict/reroute"] "[:routed-to-operator]" 0] :feed
   ["conflict" ":unrouted" [":conflict/reroute"] "[:routed-to-person]" 0] :feed
   ["conflict" ":unrouted" [":conflict/reroute"] "[]" 0] :feed
   ["conflict" ":unrouted" [":conflict/resolved"] "[:settled]" 0] :feed
   ["conflict" ":unrouted" [":conflict/settle"] "[:settled]" 0] :feed
   ["decision" ":as-promoted" [] "[:edited-in-spec]" 0] :feed
   ["decision" ":built-done" [] "[:not-built]" 0] :feed
   ["decision" ":conflicted" [":reconcile/result"] "[:drafted]" 0] :feed
   ["decision" ":conflicted" [":reconcile/result"] "[:pending]" 0] :feed
   ["decision" ":conflicted" [":reconcile/result"] "[:superseded]" 0] :feed
   ["decision" ":conflicted" [":reconcile/result"] "[]" 0] :quiet
   ["decision" ":current" [] "[:stale]" 0] :feed
   ["decision" ":decision" [":decision/owner-area"] "[]" 0] :feed
   ["decision" ":decision" [":decision/owner-area"] "[]" 1] :feed
   ["decision" ":decision" [":hold/cancel"] "[]" 0] :correction
   ["decision" ":decision" [":spec/facts"] "[]" 0] :quiet
   ["decision" ":drafted" [":promote/done"] "[:promoted]" 0] :feed
   ["decision" ":drafted" [":reconcile/result"] "[:conflicted]" 0] :feed
   ["decision" ":drafted" [":reconcile/result"] "[:pending]" 0] :feed
   ["decision" ":drafted" [":reconcile/result"] "[:superseded]" 0] :feed
   ["decision" ":drafted" [":reconcile/result"] "[]" 0] :quiet
   ["decision" ":edited-in-spec" [] "[:as-promoted]" 0] :feed
   ["decision" ":edited-in-spec" [":decision/settle-text"] "[:as-promoted]" 0] :feed
   ["decision" ":edited-in-spec" [":decision/settle-text"] "[]" 0] :feed
   ["decision" ":not-built" [] "[:built-done]" 0] :feed
   ["decision" ":pending" [":reconcile/result"] "[:conflicted]" 0] :feed
   ["decision" ":pending" [":reconcile/result"] "[:drafted]" 0] :feed
   ["decision" ":pending" [":reconcile/result"] "[:superseded]" 0] :feed
   ["decision" ":pending" [":reconcile/result"] "[]" 0] :quiet
   ["decision" ":promoted" [":reconcile/result"] "[:conflicted]" 0] :feed
   ["decision" ":promoted" [":reconcile/result"] "[:pending]" 0] :feed
   ["decision" ":promoted" [":reconcile/result"] "[:superseded]" 0] :feed
   ["decision" ":promoted" [":reconcile/result"] "[]" 0] :quiet
   ["decision" ":stale" [] "[:current]" 0] :feed
   ["decision" ":stale" [":promote/done"] "[:current]" 0] :feed
   ["decision" ":superseded" [":reconcile/result"] "[:conflicted]" 0] :feed
   ["decision" ":superseded" [":reconcile/result"] "[:drafted]" 0] :feed
   ["decision" ":superseded" [":reconcile/result"] "[:pending]" 0] :feed
   ["decision" ":superseded" [":reconcile/result"] "[]" 0] :quiet
   ["item" ":asking" [] "[:deciding]" 0] :feed
   ["item" ":asking" [] "[:needs-operator]" 0] :feed
   ["item" ":asking" [] "[:open]" 0] :feed
   ["item" ":awaiting-build" [] "[:build-starting]" 0] :feed
   ["item" ":awaiting-build" [] "[:done]" 0] :feed
   ["item" ":awaiting-build" [] "[:failed]" 0] :feed
   ["item" ":awaiting-build" [] "[:idle]" 0] :feed
   ["item" ":awaiting-build" [] "[:merged]" 0] :feed
   ["item" ":awaiting-build" [] "[:working]" 0] :feed
   ["item" ":awaiting-build" [":build/start"] "[:build-starting]" 0] :feed
   ["item" ":build-starting" [] "[:awaiting-build]" 0] :feed
   ["item" ":build-starting" [] "[:done]" 0] :feed
   ["item" ":build-starting" [] "[:failed]" 0] :feed
   ["item" ":build-starting" [] "[:idle]" 0] :feed
   ["item" ":build-starting" [] "[:merged]" 0] :feed
   ["item" ":build-starting" [] "[:working]" 0] :feed
   ["item" ":build-starting" [":correct/skip-stall"] "[:awaiting-build]" 0] :correction
   ["item" ":calm" [":item/stalled"] "[:stalled]" 0] :feed
   ["item" ":conflicted" [] "[:drafted]" 0] :feed
   ["item" ":conflicted" [] "[:spec-edited]" 0] :feed
   ["item" ":conflicted" [] "[:unreconciled]" 0] :feed
   ["item" ":deciding" [] "[:promoted]" 0] :feed
   ["item" ":done" [] "[:awaiting-build]" 0] :feed
   ["item" ":done" [] "[:build-starting]" 0] :feed
   ["item" ":done" [] "[:failed]" 0] :feed
   ["item" ":done" [] "[:idle]" 0] :feed
   ["item" ":done" [] "[:merged]" 0] :feed
   ["item" ":done" [] "[:working]" 0] :feed
   ["item" ":done" [":correct/reopen"] "[:awaiting-build]" 0] :correction
   ["item" ":drafted" [] "[:conflicted]" 0] :feed
   ["item" ":drafted" [] "[:spec-edited]" 0] :feed
   ["item" ":drafted" [] "[:unreconciled]" 0] :feed
   ["item" ":driving" [] "[]" 0] :quiet
   ["item" ":driving" [] "[]" 1] :quiet
   ["item" ":driving" [] "[]" 2] :quiet
   ["item" ":driving" [] "[]" 3] :quiet
   ["item" ":failed" [] "[:awaiting-build]" 0] :feed
   ["item" ":failed" [] "[:build-starting]" 0] :feed
   ["item" ":failed" [] "[:done]" 0] :feed
   ["item" ":failed" [] "[:idle]" 0] :feed
   ["item" ":failed" [] "[:merged]" 0] :feed
   ["item" ":failed" [] "[:working]" 0] :feed
   ["item" ":follow-up-asking" [] "[:follow-up-needs-operator]" 0] :feed
   ["item" ":follow-up-asking" [] "[:no-follow-up]" 0] :feed
   ["item" ":follow-up-needs-operator" [] "[:follow-up-asking]" 0] :feed
   ["item" ":follow-up-needs-operator" [] "[:no-follow-up]" 0] :feed
   ["item" ":gather-starting" [] "[:asking]" 0] :feed
   ["item" ":gather-starting" [] "[:asking]" 1] :feed
   ["item" ":gather-starting" [] "[:needs-operator]" 0] :feed
   ["item" ":gather-starting" [":correct/skip-stall"] "[:open]" 0] :correction
   ["item" ":idle" [] "[:awaiting-build]" 0] :feed
   ["item" ":idle" [] "[:build-starting]" 0] :feed
   ["item" ":idle" [] "[:done]" 0] :feed
   ["item" ":idle" [] "[:failed]" 0] :feed
   ["item" ":idle" [] "[:merged]" 0] :feed
   ["item" ":idle" [] "[:working]" 0] :feed
   ["item" ":item" [":hold/cancel"] "[]" 0] :correction
   ["item" ":item" [":sova.statecharts/flush"] "[]" 0] :quiet
   ["item" ":live" [":correct/relink"] "[]" 0] :correction
   ["item" ":live" [":gap/drop"] "[:dropped]" 0] :feed
   ["item" ":live" [":gather/plan"] "[]" 0] :feed
   ["item" ":live" [":hold/cancelled"] "[]" 0] :quiet
   ["item" ":live" [":hold/dropped"] "[]" 0] :quiet
   ["item" ":live" [":item/adopt"] "[]" 0] :feed
   ["item" ":live" [":link/moved"] "[]" 0] :quiet
   ["item" ":merged" [] "[:awaiting-build]" 0] :feed
   ["item" ":merged" [] "[:build-starting]" 0] :feed
   ["item" ":merged" [] "[:done]" 0] :feed
   ["item" ":merged" [] "[:failed]" 0] :feed
   ["item" ":merged" [] "[:idle]" 0] :feed
   ["item" ":merged" [] "[:working]" 0] :feed
   ["item" ":merged" [":build/start"] "[:build-starting]" 0] :feed
   ["item" ":needs-operator" [] "[:asking]" 0] :feed
   ["item" ":needs-operator" [] "[:deciding]" 0] :feed
   ["item" ":needs-operator" [] "[:open]" 0] :feed
   ["item" ":no-follow-up" [] "[:follow-up-asking]" 0] :feed
   ["item" ":no-follow-up" [] "[:follow-up-needs-operator]" 0] :feed
   ["item" ":on-hold" [":item/resume"] "[:pipeline-h]" 0] :feed
   ["item" ":open" [] "[:asking]" 0] :feed
   ["item" ":open" [] "[:deciding]" 0] :feed
   ["item" ":open" [] "[:gather-starting]" 0] :feed
   ["item" ":open" [] "[:needs-operator]" 0] :feed
   ["item" ":pipeline" [":gather/start"] "[]" 0] :feed
   ["item" ":pipeline" [":item/hold"] "[:on-hold]" 0] :feed
   ["item" ":promoted" [] "[:deciding]" 0] :feed
   ["item" ":spec-edited" [] "[:conflicted]" 0] :feed
   ["item" ":spec-edited" [] "[:drafted]" 0] :feed
   ["item" ":spec-edited" [] "[:unreconciled]" 0] :feed
   ["item" ":stalled" [":item/moved"] "[:calm]" 0] :feed
   ["item" ":unreconciled" [] "[:conflicted]" 0] :feed
   ["item" ":unreconciled" [] "[:drafted]" 0] :feed
   ["item" ":unreconciled" [] "[:spec-edited]" 0] :feed
   ["item" ":working" [] "[:awaiting-build]" 0] :feed
   ["item" ":working" [] "[:build-starting]" 0] :feed
   ["item" ":working" [] "[:done]" 0] :feed
   ["item" ":working" [] "[:failed]" 0] :feed
   ["item" ":working" [] "[:idle]" 0] :feed
   ["item" ":working" [] "[:merged]" 0] :feed
   ["org" ":org" [":hold/cancel"] "[]" 0] :correction
   ["org" ":org" [":holder/claim"] "[]" 0] :quiet
   ["org" ":org" [":holder/release"] "[]" 0] :quiet
   ["org" ":org" [":org/hours"] "[]" 0] :feed
   ["org" ":org" [":org/rename"] "[]" 0] :feed
   ["org" ":org" [":person/add"] "[]" 0] :feed
   ["org" ":org" [":project/add"] "[]" 0] :feed
   ["org" ":owner-cleared" [":owner/set"] "[:owner-none]" 0] :feed
   ["org" ":owner-cleared" [":owner/set"] "[:owner-none]" 1] :feed
   ["org" ":owner-cleared" [":owner/set"] "[:owner-set]" 0] :feed
   ["org" ":owner-cleared" [":owner/set"] "[]" 0] :feed
   ["org" ":owner-none" [] "[:owner-set]" 0] :feed
   ["org" ":owner-none" [":owner/set"] "[:owner-none]" 0] :feed
   ["org" ":owner-none" [":owner/set"] "[:owner-set]" 0] :feed
   ["org" ":owner-none" [":owner/set"] "[]" 0] :feed
   ["org" ":owner-set" [":link/moved"] "[:owner-cleared]" 0] :feed
   ["org" ":owner-set" [":owner/set"] "[:owner-none]" 0] :feed
   ["org" ":owner-set" [":owner/set"] "[:owner-set]" 0] :feed
   ["org" ":owner-set" [":owner/set"] "[]" 0] :feed
   ["person" ":active" [":person/approve"] "[]" 0] :feed
   ["person" ":active" [":person/decline"] "[]" 0] :feed
   ["person" ":active" [":person/edit"] "[:left]" 0] :feed
   ["person" ":active" [":person/edit"] "[:proposed]" 0] :feed
   ["person" ":active" [":person/edit"] "[]" 0] :feed
   ["person" ":active" [":person/leave"] "[:left]" 0] :feed
   ["person" ":active" [":person/revert"] "[:left]" 0] :feed
   ["person" ":active" [":person/revert"] "[:proposed]" 0] :feed
   ["person" ":active" [":person/revert"] "[]" 0] :feed
   ["person" ":born" [] "[:active]" 0] :feed
   ["person" ":born" [] "[:left]" 0] :feed
   ["person" ":born" [] "[:proposed]" 0] :feed
   ["person" ":left" [":person/approve"] "[]" 0] :feed
   ["person" ":left" [":person/decline"] "[]" 0] :feed
   ["person" ":left" [":person/edit"] "[:active]" 0] :feed
   ["person" ":left" [":person/edit"] "[:proposed]" 0] :feed
   ["person" ":left" [":person/edit"] "[]" 0] :feed
   ["person" ":left" [":person/revert"] "[:active]" 0] :feed
   ["person" ":left" [":person/revert"] "[:proposed]" 0] :feed
   ["person" ":left" [":person/revert"] "[]" 0] :feed
   ["person" ":person" [":hold/cancel"] "[]" 0] :correction
   ["person" ":person" [] "[]" 0] :quiet
   ["person" ":person" [":link/moved"] "[]" 0] :quiet
   ["person" ":proposed" [":person/approve"] "[:active]" 0] :feed
   ["person" ":proposed" [":person/decline"] "[:left]" 0] :feed
   ["person" ":proposed" [":person/edit"] "[:active]" 0] :feed
   ["person" ":proposed" [":person/edit"] "[:left]" 0] :feed
   ["person" ":proposed" [":person/edit"] "[]" 0] :feed
   ["person" ":proposed" [":person/leave"] "[:left]" 0] :feed
   ["person" ":proposed" [":person/revert"] "[:active]" 0] :feed
   ["person" ":proposed" [":person/revert"] "[:left]" 0] :feed
   ["person" ":proposed" [":person/revert"] "[]" 0] :feed
   ["project" ":active" [] "[:archived]" 0] :feed
   ["project" ":active" [":project/archive"] "[:archived]" 0] :feed
   ["project" ":active" [":project/unarchive"] "[]" 0] :feed
   ["project" ":archived" [":project/archive"] "[]" 0] :feed
   ["project" ":archived" [":project/unarchive"] "[:active]" 0] :feed
   ["project" ":cooling" [":cooldown/over"] "[:ready]" 0] :quiet
   ["project" ":cooling" [":cooldown/restart"] "[:cooling]" 0] :quiet
   ["project" ":has-overseer" [":overseer/clear"] "[]" 0] :feed
   ["project" ":has-overseer" [":overseer/start"] "[]" 0] :feed
   ["project" ":no-milestone" [] "[:since-post]" 0] :quiet
   ["project" ":no-overseer" [] "[:has-overseer]" 0] :feed
   ["project" ":no-overseer" [":overseer/start"] "[:has-overseer]" 0] :feed
   ["project" ":no-stakeholder" [] "[:stakeholder-set]" 0] :feed
   ["project" ":no-stakeholder" [":stakeholder/set"] "[:no-stakeholder]" 0] :feed
   ["project" ":no-stakeholder" [":stakeholder/set"] "[:stakeholder-set]" 0] :feed
   ["project" ":project" [":baton/start"] "[]" 0] :feed
   ["project" ":project" [":build/start"] "[]" 0] :feed
   ["project" ":project" [":gap/file"] "[]" 0] :feed
   ["project" ":project" [":hold/cancel"] "[]" 0] :correction
   ["project" ":project" [":milestone/noted"] "[]" 0] :quiet
   ["project" ":project" [":owner-update/post"] "[]" 0] :feed
   ["project" ":project" [":preview/start"] "[]" 0] :feed
   ["project" ":project" [":services/down"] "[]" 0] :feed
   ["project" ":project" [":services/run"] "[]" 0] :feed
   ["project" ":project" [":project/edit"] "[]" 0] :feed
   ["project" ":project" [":spec/freeze"] "[]" 0] :feed
   ["project" ":ready" [] "[:cooling]" 0] :quiet
   ["project" ":since-post" [] "[:no-milestone]" 0] :quiet
   ["project" ":stakeholder-cleared" [":stakeholder/set"] "[:no-stakeholder]" 0] :feed
   ["project" ":stakeholder-cleared" [":stakeholder/set"] "[:stakeholder-set]" 0] :feed
   ["project" ":stakeholder-set" [":link/moved"] "[:stakeholder-cleared]" 0] :feed
   ["project" ":stakeholder-set" [":stakeholder/set"] "[:no-stakeholder]" 0] :feed
   ["project" ":stakeholder-set" [":stakeholder/set"] "[:stakeholder-set]" 0] :feed
   ["reconciler" ":born" [] "[:idle]" 0] :quiet
   ["reconciler" ":born" [] "[:off]" 0] :quiet
   ["reconciler" ":debouncing" [":debounce/over"] "[:running]" 0] :quiet
   ["reconciler" ":debouncing" [":reconcile/request"] "[:running]" 0] :feed
   ["reconciler" ":debouncing" [":reconcile/request"] "[]" 0] :feed
   ["reconciler" ":failed" [] "[:off]" 0] :quiet
   ["reconciler" ":failed" [":correct/clear-failed"] "[:idle]" 0] :correction
   ["reconciler" ":failed" [":reconcile/request"] "[:debouncing]" 0] :feed
   ["reconciler" ":failed" [":reconcile/request"] "[:running]" 0] :feed
   ["reconciler" ":idle" [] "[:off]" 0] :quiet
   ["reconciler" ":idle" [":reconcile/request"] "[:debouncing]" 0] :feed
   ["reconciler" ":idle" [":reconcile/request"] "[:running]" 0] :feed
   ["reconciler" ":off" [] "[:idle]" 0] :quiet
   ["reconciler" ":off" [":reconcile/request"] "[]" 0] :feed
   ["reconciler" ":off" [":reconcile/request"] "[]" 1] :quiet
   ["reconciler" ":reconciler" [":decision/owner-area-changed"] "[]" 0] :quiet
   ["reconciler" ":reconciler" [":decision/promote"] "[]" 0] :feed
   ["reconciler" ":reconciler" [":decision/recorded"] "[]" 0] :quiet
   ["reconciler" ":reconciler" [":draft/rewrite"] "[]" 0] :feed
   ["reconciler" ":reconciler" [":effect/done"] "[]" 0] :quiet
   ["reconciler" ":reconciler" [":hold/cancel"] "[]" 0] :correction
   ["reconciler" ":reconciler" [":link/moved"] "[]" 0] :quiet
   ["reconciler" ":reconciler" [":settings/reconcile"] "[]" 0] :quiet
   ["reconciler" ":reconciler" [":settle/results"] "[]" 0] :quiet
   ["reconciler" ":reconciler" [":sova.statecharts/flush"] "[]" 0] :quiet
   ["reconciler" ":reconciler" [":spawn/next"] "[]" 0] :quiet
   ["reconciler" ":running" [":reconcile/finished"] "[:failed]" 0] :quiet
   ["reconciler" ":running" [":reconcile/finished"] "[:idle]" 0] :quiet
   ["reconciler" ":running" [":reconcile/finished"] "[:running]" 0] :quiet
   ["reconciler" ":running" [":reconcile/request"] "[]" 0] :feed
   ["reconciler" ":running" [":reconcile/stopped"] "[:failed]" 0] :quiet
   ["reconciler" ":running" [":sova/resumed"] "[:failed]" 0] :quiet
   ["residence" ":checking" [] "[:held-here]" 0] :feed
   ["residence" ":checking" [":effect/done"] "[:held-elsewhere]" 0] :feed
   ["residence" ":checking" [":effect/done"] "[:held-here]" 0] :feed
   ["residence" ":checking" [":effect/failed"] "[:held-here]" 0] :feed
   ["residence" ":clean" [":commit/look"] "[:clean]" 0] :quiet
   ["residence" ":clean" [":commit/look"] "[:committing]" 0] :quiet
   ["residence" ":clean" [":store/written"] "[:dirty]" 0] :quiet
   ["residence" ":commits" [":commit/now"] "[:committing]" 0] :feed
   ["residence" ":commits" [":effect/done"] "[]" 0] :quiet
   ["residence" ":committing" [":effect/done"] "[:clean]" 0] :quiet
   ["residence" ":committing" [":effect/done"] "[:dirty]" 0] :quiet
   ["residence" ":committing" [":effect/failed"] "[:dirty]" 0] :quiet
   ["residence" ":committing" [":store/written"] "[]" 0] :quiet
   ["residence" ":dirty" [":commit/look"] "[:committing]" 0] :quiet
   ["residence" ":dirty" [":commit/look"] "[:dirty]" 0] :quiet
   ["residence" ":held-elsewhere" [":attach/confirm"] "[:held-here]" 0] :feed
   ["residence" ":held-here" [":org/detach"] "[:detached]" 0] :feed
   ["watch" ":archived-fact" [] "[:on-shelf]" 0] :quiet
   ["watch" ":day" [":day/rollover"] "[:day]" 0] :quiet
   ["watch" ":due" [] "[:held]" 0] :quiet
   ["watch" ":due" [] "[:running]" 0] :quiet
   ["watch" ":has-overseer" [] "[:no-overseer]" 0] :quiet
   ["watch" ":held" [":reason/noted"] "[:due]" 0] :quiet
   ["watch" ":idle" [":turn/started"] "[:look-turn]" 0] :quiet
   ["watch" ":idle" [":turn/started"] "[:run-turn]" 0] :quiet
   ["watch" ":live" [] "[:paused]" 0] :quiet
   ["watch" ":loop" [":look/skipped"] "[]" 0] :quiet
   ["watch" ":loop" [":operator/run-now"] "[:running]" 0] :feed
   ["watch" ":loop" [":reason/noted"] "[]" 0] :quiet
   ["watch" ":no-overseer" [] "[:has-overseer]" 0] :quiet
   ["watch" ":on-shelf" [] "[:archived-fact]" 0] :quiet
   ["watch" ":paused" [] "[:live]" 0] :quiet
   ["watch" ":quiet" [":reason/noted"] "[:waiting]" 0] :quiet
   ["watch" ":running" [":look/finished"] "[:quiet]" 0] :quiet
   ["watch" ":running" [":look/finished"] "[:waiting]" 0] :quiet
   ["watch" ":running" [":look/not-started"] "[:waiting]" 0] :quiet
   ["watch" ":running" [":look/stopped"] "[:waiting]" 0] :quiet
   ["watch" ":running" [":sova/resumed"] "[:waiting]" 0] :quiet
   ["watch" ":turn" [":turn/ended"] "[:idle]" 0] :quiet
   ["watch" ":turn" [":turn/user-entered"] "[:operator-turn]" 0] :quiet
   ["watch" ":waiting" [":reason/noted"] "[:waiting]" 0] :quiet
   ["watch" ":waiting" [":settings/changed"] "[:waiting]" 0] :quiet
   ["watch" ":waiting" [":watch/due"] "[:due]" 0] :quiet
   ["watch" ":watch" [":facts/changed"] "[]" 0] :quiet
   ["watch" ":watch" [":ledger/reset-message"] "[]" 0] :quiet
   ["watch" ":watch" [":ledger/take"] "[]" 0] :quiet
   ["watch" ":watch" [":limit/refused"] "[]" 0] :quiet
   ["watch" ":watch" [":link/moved"] "[]" 0] :quiet
   ["watch" ":watch" [":operator/level-set"] "[]" 0] :feed
   ["watch" ":watch" [":org/attached-here"] "[]" 0] :feed
   ["watch" ":watch" [":settings/changed"] "[]" 0] :quiet
   ["watch" ":watch-off" [] "[:watch-on]" 0] :quiet
   ["watch" ":watch-on" [] "[:watch-off]" 0] :quiet})
