import type { FrontDoorConfig } from "../../shared/protocol";
import type { PeersConfig } from "./peers";

// The front door (brief: "Caddy with lb_policy first + active health checks, in an order the user
// sets"): generated here, from peers.json and the user's order, for the user to install. Sova
// never runs, writes or reloads Caddy. The directives are the lab's proven set
// (scripts/mesh-lab/lab.mjs writeCaddyfile, exercised by e2e m4).

/** A host's browser-facing address by default: its `tailscale serve` on :8443. */
export const DEFAULT_SERVE_PORT = 8443;

const origin = (host: string, port: number) => `https://${host.includes(":") ? `[${host}]` : host}:${port}`;

/**
 * The hosts in failover order: the user's `frontDoorOrder` first (ids that are no longer hosts are
 * skipped), then every host it leaves out, this host first, then peers.json order.
 * `selfDnsName` is this node's MagicDNS name when known (the mesh is on and tailscaled answered);
 * without it and without a self serveUrl, the self upstream is a placeholder the Caddyfile flags.
 */
export function frontDoorOrder(config: PeersConfig, selfDnsName: string | null): Array<{ id: string; label: string; upstream: string; placeholder?: true }> {
  const hosts = [
    {
      id: config.self.id,
      label: config.self.label,
      ...(config.self.serveUrl
        ? { upstream: config.self.serveUrl }
        : selfDnsName
          ? { upstream: origin(selfDnsName, DEFAULT_SERVE_PORT) }
          : { upstream: origin(`${config.self.id}.YOUR-TAILNET.ts.net`, DEFAULT_SERVE_PORT), placeholder: true as const }),
    },
    ...config.peers.map((p) => ({ id: p.id, label: p.label, upstream: p.serveUrl ?? origin(p.dnsName, DEFAULT_SERVE_PORT) })),
  ];
  const byId = new Map(hosts.map((h) => [h.id, h]));
  const chosen = (config.frontDoorOrder ?? []).filter((id) => byId.has(id));
  return [...chosen, ...hosts.map((h) => h.id).filter((id) => !chosen.includes(id))].map((id) => byId.get(id)!);
}

export function frontDoorConfig(config: PeersConfig, selfDnsName: string | null): FrontDoorConfig {
  const order = frontDoorOrder(config, selfDnsName);
  const flagged = order.filter((h) => h.placeholder).map((h) => h.id);
  const schemes = new Set(order.map((h) => new URL(h.upstream).protocol));
  const lines = [
    `# Sova front door, generated by Sova (GET /api/mesh/front-door). Sova never runs or writes it.`,
    `# Failover order: ${order.map((h) => h.id).join(" > ")}. The first healthy upstream serves every`,
    `# request; when it fails its health check the next one takes over, and it takes back over once`,
    `# healthy again. Change the order in Sova (Settings > Mesh), then copy this file again.`,
    `#`,
    `# Each upstream is a host's browser-facing address: by default its \`tailscale serve\` on :${DEFAULT_SERVE_PORT}`,
    `# (https, a ts.net certificate), or the serve URL set for it in Sova.`,
    ...(flagged.length
      ? [`#`, `# TODO: ${flagged.join(", ")} has no known MagicDNS name yet (the mesh is off, or tailscaled`, `# did not answer): replace YOUR-TAILNET below, or set its serve URL in Sova.`]
      : []),
    ...(schemes.size > 1
      ? [`#`, `# WARNING: Caddy needs every upstream on one scheme, and these mix http and https: give them`, `# all https (tailscale serve) or all http serve URLs, or Caddy refuses this file.`]
      : []),
    `#`,
    `# Serving this front door itself (pick one):`,
    `#  - on a tailnet node, behind \`tailscale serve --bg --https=443 http://127.0.0.1:8080\` with the site`,
    `#    address below changed to :8080 (serve then provides the ts.net certificate);`,
    `#  - or with a certificate from \`tailscale cert <name>.ts.net\`: site address <name>.ts.net and`,
    `#    \`tls <name>.ts.net.crt <name>.ts.net.key\` inside the site block.`,
    `# The front door's URL is a new browser origin: bookmarks and installed apps need the new address.`,
    `{`,
    `\tadmin localhost:2019`,
    `\tauto_https off`,
    `}`,
    ``,
    `:80 {`,
    `\treverse_proxy ${order.map((h) => h.upstream).join(" ")} {`,
    `\t\tlb_policy first`,
    `\t\tlb_try_duration 5s`,
    `\t\tlb_try_interval 250ms`,
    `\t\tfail_duration 10s`,
    `\t\thealth_uri /api/health`,
    `\t\thealth_interval 1s`,
    `\t\thealth_timeout 1s`,
    `\t\t# streamed replies (chat) pass through unbuffered`,
    `\t\tflush_interval -1`,
    `\t\t# tailscale serve routes by Host: send each upstream its own name`,
    `\t\theader_up Host {upstream_hostport}`,
    `\t\t# a dead host's address blackholes: bound the dial, and never reuse an idle upstream`,
    `\t\t# connection (a request written into a dead host's pooled connection waits forever)`,
    `\t\ttransport http {`,
    `\t\t\tdial_timeout 1s`,
    `\t\t\tkeepalive off`,
    `\t\t}`,
    `\t\t# which host answered, for debugging`,
    `\t\theader_down X-Sova-Upstream {upstream_hostport}`,
    `\t}`,
    `}`,
    ``,
  ];
  return { order: order.map(({ id, label, upstream }) => ({ id, label, upstream })), caddyfile: lines.join("\n") };
}
